"""2024 multi-seed model validation framework.

@author: Max Stoddard
"""

from scripts.python.validation.model.schema import (
    CANONICAL_VALIDATION_SEEDS,
    VALIDATION_SCHEMA_VERSION,
    VALIDATION_WINDOW_END,
    VALIDATION_WINDOW_START,
)
from scripts.python.validation.model.validation_catalog_2024 import (
    FPC_SOURCE_2024_BY_METRIC_ID,
    HPI_2024_CYCLE_PERIOD_MONTHS,
    HPI_2024_REBASED_MEAN,
    HPI_2024_REBASED_STD,
    HPI_FULL_HISTORY_REBASED_STD,
    HPI_TARGET_TOLERANCE,
    INTEREST_RATE_SPREAD_2024_QUARTERLY_MEANS,
    MARKET_SOURCE_2024_BY_METRIC_ID,
    OO_DEBT_TO_INCOME_2024_QUARTERLY_VALUES,
    RENTAL_YIELD_2024_QUARTERLY_VALUES,
    SUPPORTED_FPC_METRIC_IDS,
    TARGET_CATALOG,
    TARGETS_BY_ID,
    UKF_SOURCE_2024_BY_METRIC_ID,
    UNSUPPORTED_FPC_METRIC_IDS,
)
from scripts.python.validation.model.runner import build_validation_summary, run_validation_for_version

__all__ = [
    "CANONICAL_VALIDATION_SEEDS",
    "FPC_SOURCE_2024_BY_METRIC_ID",
    "HPI_2024_CYCLE_PERIOD_MONTHS",
    "HPI_2024_REBASED_MEAN",
    "HPI_2024_REBASED_STD",
    "HPI_FULL_HISTORY_REBASED_STD",
    "HPI_TARGET_TOLERANCE",
    "INTEREST_RATE_SPREAD_2024_QUARTERLY_MEANS",
    "MARKET_SOURCE_2024_BY_METRIC_ID",
    "OO_DEBT_TO_INCOME_2024_QUARTERLY_VALUES",
    "RENTAL_YIELD_2024_QUARTERLY_VALUES",
    "SUPPORTED_FPC_METRIC_IDS",
    "TARGET_CATALOG",
    "TARGETS_BY_ID",
    "UKF_SOURCE_2024_BY_METRIC_ID",
    "UNSUPPORTED_FPC_METRIC_IDS",
    "VALIDATION_SCHEMA_VERSION",
    "VALIDATION_WINDOW_END",
    "VALIDATION_WINDOW_START",
    "build_validation_summary",
    "run_validation_for_version",
]
