"""Compatibility wrapper for 2024 market validation metadata.

@author: Max Stoddard
"""

from __future__ import annotations

from scripts.python.validation.model.validation_catalog_2024 import (
    BOE_HOUSING_TOOLS_2024_COMPARISON_SCALE_BY_METRIC_ID,
    BOE_HOUSING_TOOLS_2024_VALUES_BY_METRIC_ID,
    HPI_2024_CYCLE_PERIOD_MONTHS,
    HPI_2024_REBASED_MEAN,
    HPI_2024_REBASED_STD,
    HPI_FULL_HISTORY_REBASED_STD,
    HPI_TARGET_TOLERANCE,
    INTEREST_RATE_SPREAD_2024_QUARTERLY_MEANS,
    MARKET_SOURCE_2024_BY_METRIC_ID,
    OO_DEBT_TO_INCOME_2024_QUARTERLY_VALUES,
    RENTAL_YIELD_2024_QUARTERLY_VALUES,
)

__all__ = [
    "BOE_HOUSING_TOOLS_2024_COMPARISON_SCALE_BY_METRIC_ID",
    "BOE_HOUSING_TOOLS_2024_VALUES_BY_METRIC_ID",
    "HPI_2024_CYCLE_PERIOD_MONTHS",
    "HPI_2024_REBASED_MEAN",
    "HPI_2024_REBASED_STD",
    "HPI_FULL_HISTORY_REBASED_STD",
    "HPI_TARGET_TOLERANCE",
    "INTEREST_RATE_SPREAD_2024_QUARTERLY_MEANS",
    "MARKET_SOURCE_2024_BY_METRIC_ID",
    "OO_DEBT_TO_INCOME_2024_QUARTERLY_VALUES",
    "RENTAL_YIELD_2024_QUARTERLY_VALUES",
]
