"""Locked 2024 target catalog for the validation framework.

@author: Max Stoddard
"""

from __future__ import annotations

from scripts.python.validation.model.fpc_source_2024 import FPC_SOURCE_2024_BY_METRIC_ID
from scripts.python.validation.model.schema import (
    FAMILY_HOUSEHOLD_DISTRIBUTION_REALISM,
    FAMILY_MACRO_CREDIT_ACTIVITY,
    FAMILY_MACRO_PRICES_LEVERAGE_AFFORDABILITY,
    FamilyDefinition,
    MetricDefinition,
    TargetBand,
)

FAMILY_DEFINITIONS: tuple[FamilyDefinition, ...] = (
    FamilyDefinition(
        family_id=FAMILY_MACRO_CREDIT_ACTIVITY,
        label="Macro Credit and Market Activity",
        weight=0.25,
    ),
    FamilyDefinition(
        family_id=FAMILY_MACRO_PRICES_LEVERAGE_AFFORDABILITY,
        label="Macro Prices, Leverage, and Affordability",
        weight=0.25,
    ),
    FamilyDefinition(
        family_id=FAMILY_HOUSEHOLD_DISTRIBUTION_REALISM,
        label="Household Distribution Realism",
        weight=0.50,
    ),
)

FAMILY_WEIGHTS = {family.family_id: family.weight for family in FAMILY_DEFINITIONS}

TARGET_CATALOG: tuple[MetricDefinition, ...] = (
    MetricDefinition(
        metric_id="core_mortgageApprovals",
        family_id=FAMILY_MACRO_CREDIT_ACTIVITY,
        label="Mortgage Approvals",
        requirement="required",
        units="count/month",
        source_label="Bank of England FPC core indicators, June 2024",
        kind="core_indicator",
        source_metadata=FPC_SOURCE_2024_BY_METRIC_ID["core_mortgageApprovals"],
        target_band=TargetBand(lower=57.0, upper=63.0),
        file_name="coreIndicator-mortgageApprovals.csv",
        scale=0.001,
    ),
    MetricDefinition(
        metric_id="core_housingTransactions",
        family_id=FAMILY_MACRO_CREDIT_ACTIVITY,
        label="Housing Transactions",
        requirement="required",
        units="count/month",
        source_label="Bank of England FPC core indicators, June 2024",
        kind="core_indicator",
        source_metadata=FPC_SOURCE_2024_BY_METRIC_ID["core_housingTransactions"],
        target_band=TargetBand(lower=84.2, upper=100.0),
        file_name="coreIndicator-housingTransactions.csv",
        scale=0.001,
    ),
    MetricDefinition(
        metric_id="core_advancesToFTB",
        family_id=FAMILY_MACRO_CREDIT_ACTIVITY,
        label="Advances to FTB",
        requirement="diagnostic",
        units="count/month",
        source_label="Unsupported by June 2024 FPC core indicators",
        kind="core_indicator",
        file_name="coreIndicator-advancesToFTB.csv",
        scale=0.001,
    ),
    MetricDefinition(
        metric_id="core_advancesToHM",
        family_id=FAMILY_MACRO_CREDIT_ACTIVITY,
        label="Advances to Home Movers",
        requirement="diagnostic",
        units="count/month",
        source_label="Unsupported by June 2024 FPC core indicators",
        kind="core_indicator",
        file_name="coreIndicator-advancesToHM.csv",
        scale=0.001,
    ),
    MetricDefinition(
        metric_id="core_advancesToBTL",
        family_id=FAMILY_MACRO_CREDIT_ACTIVITY,
        label="Advances to BTL",
        requirement="diagnostic",
        units="count/month",
        source_label="Unsupported by June 2024 FPC core indicators",
        kind="core_indicator",
        file_name="coreIndicator-advancesToBTL.csv",
        scale=0.001,
    ),
    MetricDefinition(
        metric_id="core_debtToIncome",
        family_id=FAMILY_MACRO_PRICES_LEVERAGE_AFFORDABILITY,
        label="Household Debt to Income",
        requirement="required",
        units="%",
        source_label="Bank of England FPC core indicators, June 2024",
        kind="core_indicator",
        source_metadata=FPC_SOURCE_2024_BY_METRIC_ID["core_debtToIncome"],
        target_band=TargetBand(lower=125.0, upper=145.0),
        file_name="coreIndicator-debtToIncome.csv",
    ),
    MetricDefinition(
        metric_id="core_priceToIncome",
        family_id=FAMILY_MACRO_PRICES_LEVERAGE_AFFORDABILITY,
        label="House Price to Household Disposable Income",
        requirement="required",
        units="ratio",
        source_label="Bank of England FPC core indicators, June 2024",
        kind="core_indicator",
        source_metadata=FPC_SOURCE_2024_BY_METRIC_ID["core_priceToIncome"],
        target_band=TargetBand(lower=5.4, upper=9.0),
        file_name="coreIndicator-priceToIncome.csv",
    ),
    MetricDefinition(
        metric_id="core_housePriceGrowth",
        family_id=FAMILY_MACRO_PRICES_LEVERAGE_AFFORDABILITY,
        label="House Price Growth",
        requirement="required",
        units="%",
        source_label="Bank of England FPC core indicators, June 2024",
        kind="core_indicator",
        source_metadata=FPC_SOURCE_2024_BY_METRIC_ID["core_housePriceGrowth"],
        target_band=TargetBand(lower=0.0, upper=2.0),
        file_name="coreIndicator-housePriceGrowth.csv",
    ),
    MetricDefinition(
        metric_id="core_ooDebtToIncome",
        family_id=FAMILY_MACRO_PRICES_LEVERAGE_AFFORDABILITY,
        label="Owner-Occupier Debt to Income",
        requirement="diagnostic",
        units="%",
        source_label="Unsupported by June 2024 FPC core indicators",
        kind="core_indicator",
        file_name="coreIndicator-ooDebtToIncome.csv",
    ),
    MetricDefinition(
        metric_id="core_rentalYield",
        family_id=FAMILY_MACRO_PRICES_LEVERAGE_AFFORDABILITY,
        label="Rental Yield",
        requirement="diagnostic",
        units="%",
        source_label="Unsupported by June 2024 FPC core indicators",
        kind="core_indicator",
        file_name="coreIndicator-rentalYield.csv",
    ),
    MetricDefinition(
        metric_id="core_interestRateSpread",
        family_id=FAMILY_MACRO_PRICES_LEVERAGE_AFFORDABILITY,
        label="Interest Rate Spread",
        requirement="diagnostic",
        units="%",
        source_label="Bank of England FPC core indicators, June 2024",
        kind="core_indicator",
        source_metadata=FPC_SOURCE_2024_BY_METRIC_ID["core_interestRateSpread"],
        file_name="coreIndicator-interestRateSpread.csv",
    ),
    MetricDefinition(
        metric_id="income_distribution_jsd",
        family_id=FAMILY_HOUSEHOLD_DISTRIBUTION_REALISM,
        label="Income Distribution Realism",
        requirement="required",
        units="JSD",
        source_label="WAS Round 8",
        kind="household_jsd",
        target_band=TargetBand(lower=0.0, upper=0.12),
        legacy_validation_module="income_dist",
    ),
    MetricDefinition(
        metric_id="housing_wealth_distribution_jsd",
        family_id=FAMILY_HOUSEHOLD_DISTRIBUTION_REALISM,
        label="Housing Wealth Distribution Realism",
        requirement="required",
        units="JSD",
        source_label="WAS Round 8",
        kind="household_jsd",
        target_band=TargetBand(lower=0.0, upper=0.12),
        legacy_validation_module="housing_wealth_dist",
    ),
    MetricDefinition(
        metric_id="financial_wealth_distribution_jsd",
        family_id=FAMILY_HOUSEHOLD_DISTRIBUTION_REALISM,
        label="Financial Wealth Distribution Realism",
        requirement="required",
        units="JSD",
        source_label="WAS Round 8",
        kind="household_jsd",
        target_band=TargetBand(lower=0.0, upper=0.12),
        legacy_validation_module="financial_wealth_dist",
    ),
)

TARGETS_BY_ID = {metric.metric_id: metric for metric in TARGET_CATALOG}
